FROM python:3.11-slim

# Install Chrome + ChromeDriver
RUN apt-get update && apt-get install -y wget gnupg unzip curl chromium chromium-driver \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "nightly_scraper.py"]
