[nix]
packages = [
  "python311Full",
  "chromium",
  "chromedriver",
  "curl",
  "unzip"
]

[phases.setup]
commands = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python3 -m spacy download nl_core_news_sm"
]

[start]
cmd = "streamlit run app.py --server.headless true"
