[nix]
buildInputs = [
  "python311.withPackages (ps: with ps; [ pip setuptools wheel ])",
  "chromium",
  "chromedriver",
  "curl",
  "unzip"
]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m spacy download nl_core_news_sm"
]

[start]
cmd = "streamlit run app.py --server.headless true"
