[nix]
packages = ["python310", "pip", "chromium", "chromedriver"]

[phases.setup]
nixPkgs = ['python311', 'chromium', 'chromedriver']
commands = [
  './install_chrome.sh'
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.headless true"
