[nix]
buildInputs = [
  "python311.withPackages (ps: with ps; [pip setuptools wheel])",
  "chromium",
  "chromedriver"
]

[phases.setup]
commands = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "python3 -m spacy download nl_core_news_sm"
]

[start]
cmd = "streamlit run app.py --server.headless true"
