[nix]
# Installeer python, chromium en chromedriver via nix
packages = ["python311", "chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.headless true"
