[nix]
packages = [
  "python311Full",
  "chromium",
  "chromedriver",
  "curl",
  "unzip"
]

[phases.setup]
commands = [
  "export PATH=$(dirname $(which python3)):$PATH",
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "python3 -m pip install --upgrade pip"
]

[phases.install]
cmds = [
  "python3 -m pip install -r requirements.txt",
  "python3 -m spacy download nl_core_news_sm"
]

[start]
cmd = "streamlit run app.py --server.headless true"
