[nix]
buildInputs = [
  "python311.withPackages (ps: with ps; [pip]),"
  "chromium",
  "chromedriver"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run app.py --server.headless true --server.port $PORT"
